// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz5IjrXANLnr6wMk1wttShRXGu5Q-5_8s',
    appId: '1:161141819849:web:9d75076bdc6d1713618018',
    messagingSenderId: '161141819849',
    projectId: 'student-performance-trac-80d5e',
    authDomain: 'student-performance-trac-80d5e.firebaseapp.com',
    storageBucket: 'student-performance-trac-80d5e.firebasestorage.app',
    measurementId: 'G-4WH0Y514DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_hGIZTURUvaGdu893fhQetsDg9htm7pc',
    appId: '1:161141819849:android:354e4e96d211690a618018',
    messagingSenderId: '161141819849',
    projectId: 'student-performance-trac-80d5e',
    storageBucket: 'student-performance-trac-80d5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8u5lDgcCOXyzFQNwGMhLeY1I5n7V7HVY',
    appId: '1:161141819849:ios:42d637d132db7403618018',
    messagingSenderId: '161141819849',
    projectId: 'student-performance-trac-80d5e',
    storageBucket: 'student-performance-trac-80d5e.firebasestorage.app',
    iosBundleId: 'com.example.studentPerformanceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8u5lDgcCOXyzFQNwGMhLeY1I5n7V7HVY',
    appId: '1:161141819849:ios:42d637d132db7403618018',
    messagingSenderId: '161141819849',
    projectId: 'student-performance-trac-80d5e',
    storageBucket: 'student-performance-trac-80d5e.firebasestorage.app',
    iosBundleId: 'com.example.studentPerformanceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz5IjrXANLnr6wMk1wttShRXGu5Q-5_8s',
    appId: '1:161141819849:web:5a83f3b5e000312a618018',
    messagingSenderId: '161141819849',
    projectId: 'student-performance-trac-80d5e',
    authDomain: 'student-performance-trac-80d5e.firebaseapp.com',
    storageBucket: 'student-performance-trac-80d5e.firebasestorage.app',
    measurementId: 'G-F4WKSG0C0W',
  );
}
